application/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CompanyController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('companies', [CompanyController::class, 'index'])->name('companies');
    Route::get('companies/create', [CompanyController::class, 'form'])->name('company.form');
    Route::get('companies/edit/{id}', [CompanyController::class, 'formEdit'])->name('company.form.edit');
    Route::get('companies/{id}', [CompanyController::class, 'show'])->name('company.show');
    Route::post('save_company', [CompanyController::class, 'store'])->name('company.save');
    Route::put('update_company', [CompanyController::class, 'edit'])->name('company.edit');
    Route::delete('delete_company', [CompanyController::class, 'destroy'])->name('company.destroy');
});

require __DIR__.'/auth.php';

application/app/Models/Company.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
    use HasFactory;

     /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'matricule',
        'name',
        'social_reason',
        'address',
        'phone',
        'phone2',
        'email',
        'rca',
        'trade_register',
        'logo',
        'is_active',
    ];
}

application/app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

application/app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Services\CompanyService;
use App\Entities\CompanyEntity;

class CompanyController extends Controller
{
    private CompanyService $companyService;

    public function __construct(CompanyService $companyService) {
        $this->companyService = $companyService;
    }

    public function index(){
        $companies = $this->companyService->getCompanies();
        return view("company.list", ["companies" => $companies]);
    }

    public function form(){
        return view("company.form");
    }

    public function formEdit(int $id){
        $company = $this->companyService->getCompanyById($id);
        return view("company.edit", ["company" => $company]);
    }

    public function show(int $id){
        $company = $this->companyService->getCompanyById($id);
        return view("company.show", ["company" => $company]);
    }

    //
    public function store(Request $request){
        $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255'],
        ]);

        $companyData = [
            "name" => $request->name,
            "social_reason" => $request->social_reason,
            "address" => $request->address,
            "phone" => $request->phone,
            "phone2" => $request->phone2,
            "email" => $request->email,
            "rca" => $request->rca,
            "trade_register" => $request->trade_register,
        ];

        $company = new CompanyEntity($companyData);

        $this->companyService->createCompany($company);
        return redirect()->route('companies');
    }

    public function edit(Request $request){
        $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255'],
        ]);

        $companyData = [
            "id" => $request->id,
            "name" => $request->name,
            "social_reason" => $request->social_reason,
            "address" => $request->address,
            "phone" => $request->phone,
            "phone2" => $request->phone2,
            "email" => $request->email,
            "rca" => $request->rca,
            "trade_register" => $request->trade_register,
        ];

        $company = new CompanyEntity($companyData);

        $this->companyService->updateCompany($company);
        return redirect()->route('companies');
    }

    public function destroy(int $id){
        $company = $this->companyService->deleteCompany($id);
        return view("company.show", ["company" => $company]);
    }
}

application/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

application/app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

application/app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

application/resources/views/company/edit.blade.php
<x-guest-layout>
    <x-auth-card>
        <x-slot name="logo">
            <a href="/">
                <x-application-logo class="w-20 h-20 fill-current text-gray-500" />
            </a>
        </x-slot>

        <!-- Validation Errors -->
        <x-auth-validation-errors class="mb-4" :errors="$errors" />

        <form method="PUT" action="{{ route('company.edit') }}">
            @csrf
            <!-- Name -->
            <div>
                <x-label for="name" :value="__('Name')" />
                <x-input id="name" class="block mt-1 w-full" type="text" name="name" value="{{ $company->name }}" required autofocus />
            </div>

            <!-- social reason -->
            <div>
                <x-label for="social_reason" :value="__('Social reason')" />
                <x-input id="social_reason" class="block mt-1 w-full" type="text" name="social_reason" value="{{ $company->social_reason }}" required  />
            </div>

            <!-- address -->
            <div>
                <x-label for="address" :value="__('Address')" />
                <x-input id="address" class="block mt-1 w-full" type="text" name="address" value="{{ $company->address }}" required  />
            </div>

            <!-- phone -->
            <div>
                <x-label for="phone" :value="__('Phone 1')" />
                <x-input id="phone" class="block mt-1 w-full" type="text" name="phone" value="{{ $company->phone }}" required  />
            </div>

            <!-- phone2 -->
            <div>
                <x-label for="phone2" :value="__('Phone 2')" />
                <x-input id="phone2" class="block mt-1 w-full" type="text" name="phone2" value="{{ $company->phone2 }}" />
            </div>

            <!-- Email Address -->
            <div class="mt-4">
                <x-label for="email" :value="__('Email')" />
                <x-input id="email" class="block mt-1 w-full" type="email" name="email"  value="{{ $company->email }}" required />
            </div>

            <!-- rca -->
            <div>
                <x-label for="rca" :value="__('RCA')" />
                <x-input id="rca" class="block mt-1 w-full" type="text" name="rca" value="{{ $company->rca }}" />
            </div>

            <!-- trade_register -->
            <div>
                <x-label for="trade_register" :value="__('Trade register')" />
                <x-input id="trade_register" class="block mt-1 w-full" type="text" name="trade_register" value="{{ $company->trade_register }}" />
            </div>

            <input type="hidden" name="id" value="{{ $company->id }}">

            <div class="flex items-center justify-end mt-4">
                <x-button class="ml-4">
                    {{ __('Modifier ce garage') }}
                </x-button>
            </div>
        </form>
    </x-auth-card>
</x-guest-layout>

application/resources/views/company/form.blade.php
<x-guest-layout>
    <x-auth-card>
        <x-slot name="logo">
            <a href="/">
                <x-application-logo class="w-20 h-20 fill-current text-gray-500" />
            </a>
        </x-slot>

        <!-- Validation Errors -->
        <x-auth-validation-errors class="mb-4" :errors="$errors" />

        <form method="POST" action="{{ route('company.save') }}">
            @csrf

            <!-- Name -->
            <div>
                <x-label for="name" :value="__('Name')" />
                <x-input id="name" class="block mt-1 w-full" type="text" name="name" :value="old('name')" required autofocus />
            </div>

            <!-- social reason -->
            <div>
                <x-label for="social_reason" :value="__('Social reason')" />
                <x-input id="social_reason" class="block mt-1 w-full" type="text" name="social_reason" required  />
            </div>

            <!-- address -->
            <div>
                <x-label for="address" :value="__('Address')" />
                <x-input id="address" class="block mt-1 w-full" type="text" name="address" required  />
            </div>

            <!-- phone -->
            <div>
                <x-label for="phone" :value="__('Phone 1')" />
                <x-input id="phone" class="block mt-1 w-full" type="text" name="phone" required  />
            </div>

            <!-- phone2 -->
            <div>
                <x-label for="phone2" :value="__('Phone 2')" />
                <x-input id="phone2" class="block mt-1 w-full" type="text" name="phone2" />
            </div>

            <!-- Email Address -->
            <div class="mt-4">
                <x-label for="email" :value="__('Email')" />
                <x-input id="email" class="block mt-1 w-full" type="email" name="email" :value="old('email')" required />
            </div>

            <!-- rca -->
            <div>
                <x-label for="rca" :value="__('RCA')" />
                <x-input id="rca" class="block mt-1 w-full" type="text" name="rca" />
            </div>

            <!-- trade_register -->
            <div>
                <x-label for="trade_register" :value="__('Trade register')" />
                <x-input id="trade_register" class="block mt-1 w-full" type="text" name="trade_register" />
            </div>

            <div class="flex items-center justify-end mt-4">
                <x-button class="ml-4">
                    {{ __('Creer un garage') }}
                </x-button>
            </div>
        </form>
    </x-auth-card>
</x-guest-layout>

application/resources/views/company/list.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Garages') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <a href="{{ route('company.form') }}" class="p-5 bg-success" >CREER UN GARAGE</a>
                </div>
            </div>
        </div>
        
    </div>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <table class="min-w-full divide-y divide-gray-200">
                <thead class="bg-gray-50">
                    <tr>
                        <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">#</th>
                        <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Name</th>
                        <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Social reason</th>
                        <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">address</th>
                        <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Phone 1</th>
                        {{-- <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Phone 2</th> --}}
                        <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Email</th>
                        {{-- <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">RCA</th> --}}
                        {{-- <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Trade register</th> --}}
                        <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Edit</th>
                        <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Delete</th>
                    </tr>
                </thead>
                <tbody class="bg-white divide-y divide-gray-200">
                    @php $i = 0; @endphp
                    @forelse($companies as $company)
                        @php $i++; @endphp
                        <tr>
                            <td>
                                <div class="ml-4">
                                    <div class="text-sm font-medium text-gray-900">{{ $i }}</div>
                                </div>
                            </td>
                            <td>
                                <div class="ml-4">
                                    <div class="text-sm font-medium text-gray-900">{{ $company->name }}</div>
                                </div>
                            </td>
                            <td>
                                <div class="ml-4">
                                    <div class="text-sm font-medium text-gray-900">{{ $company->social_reason }}</div>
                                </div>
                            </td>
                            <td>
                                <div class="ml-4">
                                    <div class="text-sm font-medium text-gray-900">{{ $company->address }}</div>
                                </div>
                            </td>
                            <td>
                                <div class="ml-4">
                                    <div class="text-sm font-medium text-gray-900">{{ $company->phone }}</div>
                                </div>
                            </td>
                            {{-- <td>
                                <div class="ml-4">
                                    <div class="text-sm font-medium text-gray-900">{{ $company->phone2 }}</div>
                                </div>
                            </td> --}}
                            <td>
                                <div class="ml-4">
                                    <div class="text-sm font-medium text-gray-900">{{ $company->email  }}</div>
                                </div>
                            </td>
                            {{-- <td>
                                <div class="ml-4">
                                    <div class="text-sm font-medium text-gray-900">{{ $company->rca }}</div>
                                </div>
                            </td> --}}
                            {{-- <td>
                                <div class="ml-4">
                                    <div class="text-sm font-medium text-gray-900">{{ $company->trade_register }}</div>
                                </div>
                            </td> --}}
                            <td>
                                <div class="ml-4">
                                    <div class="text-sm font-medium text-gray-900"><a href="{{ route('company.form.edit', ['id' => $company->id]) }}" class="p-5 text-info" > <span>Edit</span> </a></div>
                                </div>
                            </td>
                            <td>
                                <div class="ml-4">
                                    <div class="text-sm font-medium text-gray-900"><a href="{{ route('company.destroy', ['id' => $company->id]) }}" class="p-5 text-info" > <span>Delete</span> </a></div>
                                </div>
                            </td>
                        </tr>
                    @empty
                        
                    @endforelse
                </tbody>
            </table>
        </div>
    </div>
</x-app-layout>

application/resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <a href="{{ route('companies') }}" class="p-5 bg-success" >GARAGES</a>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

application/resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">

        <!-- Scripts -->
        <script src="{{ asset('js/app.js') }}" defer></script>
    </head>
    <body class="font-sans antialiased">
        <div class="min-h-screen bg-gray-100">
            @include('layouts.navigation')

            <!-- Page Heading -->
            <header class="bg-white shadow">
                <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
                    {{ $header }}
                </div>
            </header>

            <!-- Page Content -->
            <main>
                {{ $slot }}
            </main>
        </div>
    </body>
</html>

application/resources/views/layouts/guest.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">

        <!-- Scripts -->
        <script src="{{ asset('js/app.js') }}" defer></script>
    </head>
    <body>
        <div class="font-sans text-gray-900 antialiased">
            {{ $slot }}
        </div>
    </body>
</html>

application/resources/views/layouts/navigation.blade.php
<nav x-data="{ open: false }" class="bg-white border-b border-gray-100">
    <!-- Primary Navigation Menu -->
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex justify-between h-16">
            <div class="flex">
                <!-- Logo -->
                <div class="shrink-0 flex items-center">
                    <a href="{{ route('dashboard') }}">
                        <x-application-logo class="block h-10 w-auto fill-current text-gray-600" />
                    </a>
                </div>

                <!-- Navigation Links -->
                <div class="hidden space-x-8 sm:-my-px sm:ml-10 sm:flex">
                    <x-nav-link :href="route('dashboard')" :active="request()->routeIs('dashboard')">
                        {{ __('Dashboard') }}
                    </x-nav-link>
                </div>
            </div>

            <!-- Settings Dropdown -->
            <div class="hidden sm:flex sm:items-center sm:ml-6">
                <x-dropdown align="right" width="48">
                    <x-slot name="trigger">
                        <button class="flex items-center text-sm font-medium text-gray-500 hover:text-gray-700 hover:border-gray-300 focus:outline-none focus:text-gray-700 focus:border-gray-300 transition duration-150 ease-in-out">
                            <div>{{ Auth::user()->name }}</div>

                            <div class="ml-1">
                                <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                                    <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
                                </svg>
                            </div>
                        </button>
                    </x-slot>

                    <x-slot name="content">
                        <!-- Authentication -->
                        <form method="POST" action="{{ route('logout') }}">
                            @csrf

                            <x-dropdown-link :href="route('logout')"
                                    onclick="event.preventDefault();
                                                this.closest('form').submit();">
                                {{ __('Log Out') }}
                            </x-dropdown-link>
                        </form>
                    </x-slot>
                </x-dropdown>
            </div>

            <!-- Hamburger -->
            <div class="-mr-2 flex items-center sm:hidden">
                <button @click="open = ! open" class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 focus:text-gray-500 transition duration-150 ease-in-out">
                    <svg class="h-6 w-6" stroke="currentColor" fill="none" viewBox="0 0 24 24">
                        <path :class="{'hidden': open, 'inline-flex': ! open }" class="inline-flex" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
                        <path :class="{'hidden': ! open, 'inline-flex': open }" class="hidden" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                    </svg>
                </button>
            </div>
        </div>
    </div>

    <!-- Responsive Navigation Menu -->
    <div :class="{'block': open, 'hidden': ! open}" class="hidden sm:hidden">
        <div class="pt-2 pb-3 space-y-1">
            <x-responsive-nav-link :href="route('dashboard')" :active="request()->routeIs('dashboard')">
                {{ __('Dashboard') }}
            </x-responsive-nav-link>
        </div>

        <!-- Responsive Settings Options -->
        <div class="pt-4 pb-1 border-t border-gray-200">
            <div class="px-4">
                <div class="font-medium text-base text-gray-800">{{ Auth::user()->name }}</div>
                <div class="font-medium text-sm text-gray-500">{{ Auth::user()->email }}</div>
            </div>

            <div class="mt-3 space-y-1">
                <!-- Authentication -->
                <form method="POST" action="{{ route('logout') }}">
                    @csrf

                    <x-responsive-nav-link :href="route('logout')"
                            onclick="event.preventDefault();
                                        this.closest('form').submit();">
                        {{ __('Log Out') }}
                    </x-responsive-nav-link>
                </form>
            </div>
        </div>
    </div>
</nav>